inherit_from:
  - '~/configs/.rubocop.yml'

AllCops:
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
  Exclude:
    - 'test/**/*'

Layout/AccessModifierIndentation:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/HashAlignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
